name: Unit Tests

on:
  - workflow_call

jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3

      - name: Wait for Docker daemon to be ready
        run: |
          echo "Waiting for Docker daemon to be available..."
          until docker info >/dev/null 2>&1; do sleep 2; done

      - name: Copy .env
        run: cp .env.example .env

      - name: Run unit tests
        working-directory: ./apps/backend
        run: |
          docker compose --profile test-unit up --build --abort-on-container-exit

      - name: Tear down test containers
        if: always()
        working-directory: ./apps/backend
        run: |
          docker compose --profile test-unit down -v
